set nocompatible
filetype off

" set encoding
"set enc=utf-8,cp949
"se enc=utf-8
"se fenc=utf-8
"se langmenu=cp949
" set fenc=utf-8,cp949,cp932,euc-jp,shift-jis,big5,ucs-2le,latin1

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
" set rtp+=%userprofile%/.vim/bundle/Vundle.vim/
" call vundle#begin('%userprofile%/.vim/bundle')

Bundle 'gmarik/vundle'


Plugin 'The-NERD-tree'
nmap <F7> :NERDTreeToggle<CR>


Plugin 'AutoComplPop'


Plugin 'taglist-plus'
nmap <F8> :TlistToggle<CR>
let Tlist_Inc_Winwidth = 0
let Tlist_Exit_OnlyWindow = 0
let Tlist_Auto_Open = 0
let Tlist_Use_Right_Window = 1

" plugins for colors
Plugin 'altercation/vim-colors-solarized'
Plugin 'sickill/vim-monokai'

"Plugin 'mattn/vimtweak'
"Plugin 'mattn/transparency-windows-vim'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

set ls=2

" plugins for go
Plugin 'fatih/vim-go'
"Plugin 'Valloric/YouCompleteMe'
Plugin 'majutsushi/tagbar'

Plugin 'JamshedVesuna/vim-markdown-preview'

Plugin 'osyo-manga/vim-over'
" nnoremap <silent><leader>m :OverCommandLine<cr>%s/


" plugins for rust
Plugin 'rust-lang/rust.vim'

Plugin 'racer-rust/vim-racer'
set hidden

Plugin 'scrooloose/syntastic'
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1


filetype plugin indent on


scripte utf-8

" vim functions
set nocp

" recover options
" set all&

" commands history
set hi=100

" use backspace
set bs=indent,eol,start


" show always cursor position
set ru

" show command completing
set sc

" number line
set nu

" line width
set nuw=5

" indentation
set smartindent
set autoindent

" magic feature
set magic

" visual mode
set sel=exclusive

" matching parenthesis
set mps+=<:>
set sm

" highlight searchcase
set hlsearch

" ignore case in search
set ignorecase

" smart case check
" set ic

" tabs
set tabstop=4
set shiftwidth=4
set expandtab

" turnon syntax highlight by file ext
sy enable

" set themes
if has('gui_running')
    set background=light
    "colors evening
    "colors torte
    "colors morning
    "colors desert
    colors monokai
endif

" highlight cursorline
set cursorline

" hilight colorcolumn
"set cc=51,81,121
"hilight ColorColumn ctermbg=17 guibg=navyblue
let &colorcolumn=join(range(81,999),",")
hi ColorColumn guibg=#000020 ctermbg=17

"fonts
"se gfn=Liberation_Mono:b:h10
"se gfn=D2Coding:h10
"se guifont=CPMono_v07Plain:h10:cANSI:qDRAFT
"se gfn=Dejavu_Sans_Mono:h10
"se gfn=Consolas:h10
"se gfn=Courier_New:h10
"se gfn=Consolas:b:h10.2
"se gfn=Source_Code_Pro_Medium:h10
"se gfn=Courier:h10
"se gfn=Menlo:h10
"se gfn=IBM_3270:h13:cANSI:qDRAFT
"se gfn=Fixedsys:h12
"se gfn=NetTerm_ANSI:h12:cANSI:qDRAFT
"se gfn=Fira_Mono_Medium:h10:cANSI:qDRAFT
se gfn=Hack:h10:b:cANSI:qDRAFT
"se gfn=Droid_Sans_Mono:h10:cANSI:qDRAFT
"se gfn=ProFontWindows:h10:cANSI:qDRAFT
"se gfn=Inconsolata:h10:cANSI:qDRAFT
"se gfn=Dina_TTF:h10
"se gfn=Classic_Console:h16
"se gfn=Lucida_Sans_Typewriter:h10

"se linespace=3
"se gfn=Fixedsys:h12
"se guifontwide=Dalsebeol:h12

